# -*- coding: utf-8 -*-
"""TESLA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XbsnaPk76qFWtyrbyad48p1bB4or6dS
"""



import os
import joblib
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


tesla_df = pd.read_csv('/content/drive/MyDrive/University /Trimester 2/Software tech/TESLA.csv')


tesla_df['Date'] = pd.to_datetime(tesla_df['Date'])


tesla_df = tesla_df.dropna()


tesla_df = tesla_df[tesla_df['Close'] > 0]
tesla_df['log_price'] = np.log(tesla_df['Close'])


X = tesla_df[['Open', 'High', 'Low', 'Volume']]
y = tesla_df['log_price']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


models = {
    'Linear Regression': LinearRegression(),

}


checkpoint_path = "/content/drive/MyDrive/model_checkpoints_tesla/"


if not os.path.exists(checkpoint_path):
    os.makedirs(checkpoint_path)


for name, model in models.items():
    model_checkpoint = f"{checkpoint_path}{name}_checkpoint.pkl"


    if os.path.exists(model_checkpoint):
        print(f"Loading checkpoint for {name}...")
        model = joblib.load(model_checkpoint)
    else:
        model.fit(X_train, y_train)
        joblib.dump(model, model_checkpoint)


    y_pred = model.predict(X_test)
    print(f"{name} R^2 score: {r2_score(y_test, y_pred)}")

print("Model training complete. Checkpoints saved.")